volumes:
  AlgoTerminalDevEnv-shell-history: # This basically lets docker auto-manage this volume.

services:
  algoterminaldev:
    profiles:
      - development
    # platform: linux/amd64 # We force the platform for consistency.
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock # Forwards the local Docker socket to the container.
      - ..:/algoterminal # Mount the local git directory into the container. We can use this to shuttle files back and forth as well.
      - AlgoTerminalDevEnv-shell-history:/root/.zsh_history # Mount the shell history volume
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/zsh -c "while sleep 1000; do :; done"
    # Enable privileged mode if needed for network operations
    # privileged: true
    # env_file: devcontainer.env
    environment:
      - DUMMY=1 # Fixed: Use = instead of : for environment variables
      # We can use this to add any env vars we need for local development. Secrets should be referenced through env or a local env file.
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # ports:
    #   - "127.0.0.1:7497:7497"
    #   - "127.0.0.1:4002:4002"
